development:
  api_http_auth:
    username: 'test'
    password: 'secret'

test:
  api_http_auth:
    username: 'test'
    password: 'secret'

production:
  api_http_auth:
    username: <%= ENV['API_HTTP_AUTH_USERNAME'] %>
    password: <%= ENV['API_HTTP_AUTH_PASSWORD'] %>
